### ISSUE TITLE
CSV export issue

### ISSUE THREAD

**Issue by Segfaultd** [ForestAdmin/agent-nodejs#460] opened 2022-09-30 16:55 UTC
## Expected behavior

When doing a CSV export, it's missing more than half of the collection

## Actual behavior

The exported collection only contains 1985 entries.

When clicking on export collection, I get an alert saying

"Are you sure you want to download all these 4231 subscriptions?"

## Failure Logs

None

## Context

I run this on an Express raw application

- Package Version:

```
"@forestadmin/agent": "^1.0.0-beta.60",
"@forestadmin/datasource-sql": "^1.0.0-beta.53",
"@forestadmin/datasource-toolkit": "^1.0.0-beta.34",
```

**Comment by romain-gilliotte** [comment] 2022-10-03 10:31
Can you give me any more info so that I can try to reproduce?
Is there an error stack or anything else that could help me with that?

**Comment by Segfaultd** [comment] 2022-10-03 10:57
Nothing specific, no error. It "works" but missing a few hundreds entity. May I give you an env ID where you can try it by yourself?

**Comment by Segfaultd** [comment] 2022-10-12 15:05
Hello @romain-gilliotte any chance you had the time to look into that issue? Would be nice to move forward on it :D Thanks!

**Comment by jeffladiray** [comment] 2022-10-25 15:18
Hey @Segfaultd :wave:

Maybe @romain-gilliotte has more insight than I do, however I'm not able to reproduce on my end either.

Do you eventually have a reproduction repository?
Could you maybe share your project name/environment name so I can check what is happening on my end?
Finally, could you share the DDL or structure definition of the table that fails during the export?

Thanks in advance :pray:

**Comment by jeffladiray** [comment] 2022-10-26 07:22
Project name can be shared publicly (This is the very first thing we ask for on our [Community](https://community.forestadmin.com/))

We usually ask for this information in order to visualize your project configuration (Environments, layout etc).

> By going to the staging environment on it and trying to export data, you would see what's actually going on.

[By design](https://docs.forestadmin.com/developer-guide-agents-nodejs/getting-started/how-it-works), ForestAdmin can't do that :)
As the Forestadmin agent is hosted on your end, we can't really debug agent side issues on our end.

In your case, and as I'm not able to reproduce on the databases I have on my end, I'm guessing the issue either comes from an issue in this repository, or something related to your database structure.

**Comment by jeffladiray** [comment] 2022-10-26 12:06
> No, I meant, that you can access the web UI on app.forestadmin.com for my project

That was my point, we (ForestAdmin developers) can't do that. Even though I can get the API Endpoint of your agent on my end, I can't query your agent to "try to export some data", as I'm not authorized on your project, and I have no way to get authentified on your agent.

That's why I was asking about models definition, so I can setup and maybe get a reproductible example on my end.

Running exports on the `_example` folder of this package exports records correctly, so as of now, I'm not able to reproduce this issue without further informations regarding your agent configuration/models definition.

**Comment by Segfaultd** [comment] 2022-10-26 12:27
Got it. Thanks for clarifying out that point.

I can maybe try to debug that out. Would you point me to the file that handles the export? I can try to put comments in it on my local setup and see how it goes. Thanks

**Comment by jeffladiray** [comment] 2022-10-26 12:45
If you encounter the issue on the main table view (And not in the related data), the route is directly exposed [here](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/agent/src/routes/access/csv.ts)

CSV generator is the all-datasource business implementation ([here](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/agent/src/utils/csv-generator.ts))

It is based on the `list` function, that is exposed by the datasource you are using (Most likely the SQL datasource)

**Comment by Segfaultd** [comment] 2022-10-26 12:57
This is what the UI is saying

![Capture d’écran 2022-10-26 à 14 55 34](https://user-images.githubusercontent.com/5221072/198031383-fc89d3ee-59ed-4c92-ab1a-d72cf88fa107.png)

I added these comments:

```
const records = await list(caller, new datasource_toolkit_1.PaginatedFilter(copiedFilter), projection);
console.log('Got records', records.length);
```
And this is what is getting logged. Something is clearly broken on the iterator. Also worth to mention that's its always failing at 1985 entities, no matter the table i'm trying to export.

![Capture d’écran 2022-10-26 à 14 56 37](https://user-images.githubusercontent.com/5221072/198031580-7864713c-605e-4251-aa73-c86eee05c6a7.png)

**Comment by Segfaultd** [comment] 2022-10-26 13:08
Just got it working by removing these two lines

```
if (limit < skip)
                currentPageSize = skip - limit;
```

Now the export is correctly working :')

**Comment by Scra3** [comment] 2022-11-02 10:22
Hello, we have merged a patch :)
Please upgrade your agent version to the latest and tell us if the patch fixes your bug 🙏 .

**Comment by Segfaultd** [comment] 2022-11-02 10:57
@Scra3 Hello, and thank you for your feedback. Perfectly working now! :)

**Comment by Scra3** [comment] 2022-11-02 10:59
Super happy for you :) Have a good time with our agent :)

**Closed** 2022-11-03 14:17 UTC
