### ISSUE TITLE
ECONNREFUSED with NestJS

### ISSUE THREAD

**Issue by Segfaultd** [ForestAdmin/agent-nodejs#404] opened 2022-09-04 20:47 UTC
### Introduction

I have made a sample integration to one of my NestJS backends:

```
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';

import { createAgent } from '@forestadmin/agent';
import { createSqlDataSource } from '@forestadmin/datasource-sql';

import { AppModule } from './app.module';

async function bootstrap() {
    // Construct the nest application
    const app: NestExpressApplication = await NestFactory.create<NestExpressApplication>(AppModule);

    // Set the multiple options
    app.setGlobalPrefix('v1');
    app.enableCors();
    app.enable('trust proxy');

    // Bind the Forest Admin middleware
    const agent = createAgent({
        authSecret: process.env.FOREST_AUTH_SECRET,
        agentUrl: process.env.FOREST_AGENT_URL,
        envSecret: process.env.FOREST_ENV_SECRET,
        isProduction: process.env.NODE_ENV === 'production',
    });
    await agent.addDataSource(createSqlDataSource(process.env.DATABASE_URL)).mountOnNestJs(app).start();


    await app.listen(process.env.PORT || 3000);
}

bootstrap();
```

Running that very simple sample will throw the following error

```
info: Successfully mounted on NestJS
warning: options.clientId was not provided. Using Node.js cluster mode, or multiple instances of the agent will break authentication (For more information: https://docs.forestadmin.com/beta-developer-guide-agents-v2/extra-helps/running-forest-admin-on-multiple-instances)
info: Schema was not updated since last run
(node:17092) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems that it's failing to upload sources to ForestAdmin api, because if I set the forestServerUrl parameter to anything else, it would just timeout or endup with the following error

```
info: Successfully mounted on NestJS
warning: options.clientId was not provided. Using Node.js cluster mode, or multiple instances of the agent will break authentication (For more information: https://docs.forestadmin.com/beta-developer-guide-agents-v2/extra-helps/running-forest-admin-on-multiple-instances)
(node:17127) UnhandledPromiseRejectionWarning: Error: ForestAdmin server failed to find the project related to the envSecret you configured. Can you check that you copied it properly in the Forest initialization?
    at Function.handleResponseError (/Users/enguerrand/dev/datacube/backend/node_modules/@forestadmin/agent/src/agent/utils/forest-http-api.ts:242:15)
    at Function.hasSchema (/Users/enguerrand/dev/datacube/backend/node_modules/@forestadmin/agent/src/agent/utils/forest-http-api.ts:116:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ForestAdminHttpDriver.sendSchema (/Users/enguerrand/dev/datacube/backend/node_modules/@forestadmin/agent/src/agent/forestadmin-http-driver.ts:38:27)
    at AgentBuilder.start (/Users/enguerrand/dev/datacube/backend/node_modules/@forestadmin/agent/src/builder/agent.ts:225:5)
    at bootstrap (/Users/enguerrand/dev/datacube/backend/src/main.ts:26:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Package Version:
"@forestadmin/agent": "^1.0.0-beta.49",
"@forestadmin/datasource-sql": "^1.0.0-beta.43",
"@nestjs/core": "^9.0.11",

**Comment by jeffladiray** [comment] 2022-09-05 06:52
Hey @Segfaultd 

I can see that the agent is mounted after enabled CORS on your Nest.js app, and our agent handles CORS (as well as multiple other middleware) itself, so this can be the issue here.
Eventually, could you try the following and tell me if it works ?

```typescript
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';

import { createAgent } from '@forestadmin/agent';
import { createSqlDataSource } from '@forestadmin/datasource-sql';

import { AppModule } from './app.module';

async function bootstrap() {
    // Construct the nest application
    const app: NestExpressApplication = await NestFactory.create<NestExpressApplication>(AppModule);

    // Set the multiple options
    app.setGlobalPrefix('v1');

    // Bind the Forest Admin middleware
    const agent = createAgent({
        authSecret: process.env.FOREST_AUTH_SECRET,
        agentUrl: process.env.FOREST_AGENT_URL,
        envSecret: process.env.FOREST_ENV_SECRET,
        isProduction: process.env.NODE_ENV === 'production',
    });
    await agent.addDataSource(createSqlDataSource(process.env.DATABASE_URL)).mountOnNestJs(app).start();

    app.enableCors();
    app.enable('trust proxy');

    await app.listen(process.env.PORT || 3000);
}

bootstrap();
```

**Comment by Segfaultd** [comment] 2022-09-05 06:54
Hey @jeffladiray, thank you for your quick update.
Just gave it a try and did not change much, I still have the same error.

What could it be trying to reach when using 127.0.0.1:443 ?

Thank you

**Comment by jeffladiray** [comment] 2022-09-05 07:01
Well, in the stacktrace you shared, it seems that this is this [call failing](https://github.com/ForestAdmin/agent-nodejs/blob/b69c977ecf081031ea1c1cf65ecd61116063ffd2/packages/agent/src/agent/utils/forest-http-api.ts#L110).

`forestServerUrl` defaults to `https://api.forestadmin.com`, so I'm not sure why this would result in a `127.0.0.1:443` call.
Do you have any kind of configuration that would prevent the agent to have access to `api.forestadmin.com ?

**Comment by Segfaultd** [comment] 2022-09-05 07:10
None, and both ping to the domain or browser request works just fine. Weird 🤔

**Comment by jeffladiray** [comment] 2022-09-05 09:35
Very weird indeed. I'm currently unable to reproduce the issue.
Would it be possible for you to add a debugger to check what is happening?

**Comment by Segfaultd** [comment] 2022-09-05 21:31
I have been able to trace down the error to that very specific line: 
https://github.com/ForestAdmin/agent-nodejs/blob/b69c977ecf081031ea1c1cf65ecd61116063ffd2/packages/agent/src/agent/forestadmin-http-driver.ts#L25

Everything logged before that is printed out, everything after that isn't. Guess that's the issue. Any idea?

**Comment by jeffladiray** [comment] 2022-09-06 13:20
Could you confirm that FOREST_ENV_SECRET is correctly set in your `createAgent` file ?

**Comment by Segfaultd** [comment] 2022-09-07 17:25
Finally found something interesting.

Upgrading the following dependencies made the whole thing work:

- node-mailjet
- stripe
- redis

Dunno exactly which one did fix the issue, but so far something was broken with old versions.

Thank you for your help @jeffladiray

**Comment by jeffladiray** [comment] 2022-09-08 08:29
Definitely weird indeed.
I'll do a quick check to see what was the issue with the dependencies you shared (And do a possible fix if I find something), but since it seems to be resolved on your end, so I'll close the issue :)

**Closed by jeffladiray** 2022-09-08 08:29 UTC
